FE-1062: unsaved mods
rbkmoney/control-center pull request #171
Opened 2020-08-26 09:00 UTC by Roniakia

2020-08-31 17:10 UTC, KeinAsylum requested changes
PartyClaimService
* Лучше переименовать в FetchClaimService и вынести во вне параметры partyID, claimID. Т.к они уже достаются в PartyClaimComponent
* Возвращать `return of(e);` не совсем верно, потому что в claim$ попадет объект ошибки и в дальнешем все поломается. Пример как можно обработать: src/app/sections/payment-section/reports/cancel-report/cancel-report.service.ts (dashboard)

PartyClaimActionsComponent
* Сейчас он пустой, в дальнейшем нужно вынести это в модуль

TimelineItemsModule
* Убрать index, добавить всем подмодулям MenuConfig:
```typescript
interface MenuConfig {
    action: MenuConfigAction; // DeleteComment, EditPartyModification e.t.c
    label: string;
}
```
```
<cc-comment-timeline-item ... [menuConfig]="commentMenuConfig" (menuItemSelected)="commentMenuItemSelected($event, index)"></cc-comment-timeline-item>
```

Сделать реорганизацию папки claim-changeset:
```
changeset/
    claim-changeset/
    unsaved-changeset/
    ... // остальные модули из claim-changeset
    index.ts
```

UnsavedClaimChangesetService
* Распелить на отдельные сервысы, по одной независимой задаче на сервис

EditUnsavedModificationComponent
* Выделить в модуль, работа с диалогом должна быть сосредоточена в этом модуле (Пример в dashboard: src/app/sections/payment-section/reports/create-report/create-report.module.ts)

2020-09-03 12:32 UTC, KeinAsylum requested changes
* Каждый компонент с menuConfig имеет внутри себя идентичную логику по обработки этого конфига. Можно выделить в отдельный модуль

2020-09-03 12:32 UTC, KeinAsylum commented on src/app/sections/party-claim/changeset/timeline-items/menu-config.ts
> +    label?: string;
В каких случаях он может не указываться?

2020-09-03 12:32 UTC, KeinAsylum commented on src/app/sections/party-claim/fetch-claim.service.ts
>      claim$ = this.getClaim$.asObservable().pipe(
asObservable вызывать не обязательно

2020-09-03 12:32 UTC, KeinAsylum commented on src/app/sections/party-claim/fetch-claim.service.ts
> +                    return of('error');
Сейчас никак не узнать на UI что проихошла ошибка. Нужно показыать SnackBar. Заведи в этом сервисе состояние error и покажи SnackBar в компоненте

2020-09-03 12:32 UTC, KeinAsylum commented on src/app/sections/party-claim/_party-claim-theme.scss
> +@import 'changeset/timeline-components/timeline-item-loading/timeline-item-loading-theme';
Импорт испортился

2020-09-03 13:45 UTC, Roniakia commented on src/app/sections/party-claim/fetch-claim.service.ts
> +                    return of('error');
Б_Б

2020-09-03 18:04 UTC, KeinAsylum approved these changes

2020-09-04 07:42 UTC, merged