FE-1062: extractor
rbkmoney/control-center pull request #180
Opened 2020-09-10 08:44 UTC by Roniakia

2020-09-10 23:29 UTC, Roniakia commented
@KeinAsylum B)

2020-09-16 11:52 UTC, KeinAsylum requested changes
Нужно добавить проверок, например падают ошибки:
http://localhost:7000/party/4893b9d7-1962-4c49-be28-2bab64065904/claim/8178
Поправь не только этот кейс, но и все схожие

Вижу в некоторых модулях отсутсвуют index.ts файлы, из-за чего не понятно чем можно пользоваться из вне и получаются не очень красивые импорты

Под экстрактор лучше завести модуль, который будет отдавать наружу сервис, который в свою очередь вызывает диалог, обрабатывает результат после открытия и проч.
Можно сделать по аналогии с src/app/sections/payment-section/reports/create-report в dashboard

2020-09-16 11:52 UTC, KeinAsylum commented on src/app/sections/party-claim/changeset/claim-changeset/claim-changeset.component.ts
> +            this.changesetInfos$.getValue()[i],
Потенциальное место где произойдет ошибка

2020-09-23 09:42 UTC, KeinAsylum approved these changes

2020-09-23 17:26 UTC, merged