[WIP] Payments filters
rbkmoney/control-center pull request #194
Opened 2020-10-09 00:45 UTC by Roniakia

2020-10-14 15:12 UTC, KeinAsylum requested changes
* PaymentsSearcherModule - нужно убрать зависимость от Route
* PaymentsSearcherComponent, PaymentsMainSearchFiltersComponent. Не совсем понятно для чего нужен `partyID` и почему его можно не указывать. Как по мне лучше ввести термин: `type`:

```typescript
interface SearcherType {
    type: 'PartySearcher' | 'GlobalSearcher';
    partyID?: string;
}
```
* Нужно убрать магазин из таблицы в GlobalSearcher

2020-10-18 16:15 UTC, KeinAsylum requested changes

2020-10-18 16:15 UTC, KeinAsylum commented on src/app/shared/components/payments-searcher/payments-searcher.service.ts
> +    );
* removeEmptyProperties был нужен для того, чтобы в route не попадали пустые параметры. Это действие уже производится в QueryParamsStore;
* distinctUntilChanged — я как понимаю это попытка пофиксить дублирущий запрос на поиск. Дублирование запроса происходит потому, что после инициализации компоненты: cc-payments-main-search-filters и cc-payments-other-search-filters делают valueChanges. Т.к компоненты инициализируются одновременно, то и значение сюда приходит 2 раза подрят от разных компонентов. И значания эти могут быть совершенно разными. По этому distinctUntilChanged не подходит. Используй skip(1), и не помещай ничего после shareReplay, это не правильно.

2020-10-19 11:16 UTC, Roniakia commented on src/app/shared/components/payments-table/payments-table.component.ts
> +    constructor(private router: Router) {}
Не вижу в этом что-то плохое, ведь тут он используется для перехода в детали платежа. Считаю, что делать Output event с сгенеренным линком чтобы родитель уже сам переходил в детали платежа оверинжинирингом.
Детали платежа всегда одни и других не может быть. Что-то делать с этим имеет смысл только если будет динамическое меню которого не планируется тут.

2020-10-20 12:36 UTC, KeinAsylum approved these changes

2020-10-20 12:37 UTC, merged