Role mgt refactoring
rbkmoney/control-center pull request #201
Opened 2020-10-21 12:12 UTC by KeinAsylum

2020-10-22 11:51 UTC, Roniakia submitted a review, later dismissed
Мне норм, разве что возможно вынесла бы енами ролей в отдельный файлы.

2020-10-22 12:23 UTC, DenisHedgehog commented
![image](https://user-images.githubusercontent.com/17727894/96871047-651e9200-147a-11eb-936b-13f16aec7338.png)
В проекте присутствуют места, где используется роль "claim:get", но в энамах эта роль помечена как неиспользованная.

2020-10-22 12:25 UTC, DenisHedgehog commented
![image](https://user-images.githubusercontent.com/17727894/96871332-ce9ea080-147a-11eb-948b-0af120ca8226.png)
И вот еще захардкоженая роль

2020-10-22 12:57 UTC, KrickRay requested changes

2020-10-22 12:57 UTC, KrickRay commented on src/app/sections/party/party.component.ts
> +    }
не уверен насчет такого подхода с activateRoles. получается информация о доступности по определенному урлу будет хранится везде где пишем урл, нужно, думаю, где-то брать об этом информацию (сервис/константа)

2020-10-22 12:57 UTC, KrickRay commented on src/app/sections/party/party.component.ts
> +    }
почему бы не просто: 
```
links = this.getLinks();
```

2020-10-22 12:57 UTC, KrickRay commented on src/app/shared/services/app-auth-guard.service.ts
> +    }
как я понимаю у этих методов общая часть
```ts
!environment.production || (Array.isArray(this.roles) && roles.every((v) => this.roles.includes(v)))
```

2020-10-22 12:57 UTC, KrickRay commented on src/app/shared/services/app-auth-guard.service.ts
> +        return !environment.production || roles.some((role) => userRoles.includes(role));
странно написан этот метод:
- почему-то some
- и по другому берутся роли

2020-10-22 12:57 UTC, KrickRay commented on src/app/sections/party/party.component.ts
> +    }
подумал можно достать data по урлу но не нашел такого способа

2020-10-23 13:48 UTC, KeinAsylum commented on src/app/shared/services/app-auth-guard.service.ts
> +// Unused:
Самое простое: можно вывести в консоль при необходимости, это вроде и так очевидно

2020-10-23 13:48 UTC, KeinAsylum commented on src/app/sections/party/party.component.ts
> +    }
Обсудали утром, что пока нет однозначного способа

2020-10-23 14:55 UTC, KeinAsylum commented on src/app/shared/services/app-auth-guard/app-auth-guard.service.ts
> +        return isRolesAllowed(this.keycloakAngular.getUserRoles(), roles);
Роли берутся через: `this.keycloakAngular.getUserRoles()`, потому что `this.roles` возвращает `undefined` в `app.component`. Пробовал разные способы, не понятно почему так происходит.

2020-10-23 15:02 UTC, KrickRay approved these changes

2020-10-23 15:25 UTC, merged