Payment details extended by terminal n provider n contractor
rbkmoney/control-center pull request #217
Opened 2020-11-18 23:40 UTC by Roniakia

2020-11-19 10:21 UTC, KeinAsylum requested changes
* Добавить обработку ошибки платежа
* Вынести Terminal, Provider в отдельные компоненты. Добавить в обработку состояний loading, error
* Выполняется 2 одинаковых запроса на /parties, при первой загрузке: 3

2020-11-19 12:19 UTC, jayhoney commented on src/app/papi/party.service.ts
> +        this.getParty(partyID).pipe(pluck('contracts'));
Why you don't like return?

2020-11-19 12:59 UTC, Roniakia commented on src/app/papi/party.service.ts
> +        this.getParty(partyID).pipe(pluck('contracts'));
Да просто не нравится его делать на одностраничных методах

2020-11-19 16:29 UTC, jayhoney approved these changes

2020-11-20 12:32 UTC, KeinAsylum requested changes

2020-11-20 12:32 UTC, KeinAsylum commented on src/app/sections/payment-details/payment-main-info/payment-contractor/fetch-contractor.service.ts
> +    );
У тебя дублируются запросы тут. Ты дергаешь `this.partyService.getContract`, `this.partyService.getContractor`, которые каждый раз перезапрашивают party

2020-11-20 13:35 UTC, Roniakia commented on src/app/sections/payment-details/payment-main-info/payment-contractor/fetch-contractor.service.ts
> +    );
Я знаю

2020-11-20 16:21 UTC, KeinAsylum approved these changes

2020-11-20 16:29 UTC, KeinAsylum approved these changes

2020-11-20 16:51 UTC, merged