Small fixes 'n' shop-providers
rbkmoney/control-center pull request #220
Opened 2020-12-08 06:50 UTC by Roniakia

2020-12-08 08:17 UTC, jayhoney commented on src/app/sections/shop-details/shop-providers/services/fetch-shop-providers/extract-terminal-infos.ts
> +interface PredicateInfo {
Move all interfaces in types directory

2020-12-08 08:17 UTC, jayhoney commented on src/app/sections/shop-details/shop-providers/services/fetch-shop-providers/extract-terminal-infos.ts
> +interface PredicateInfo {
Not all of them may be exportable

2020-12-08 11:48 UTC, KeinAsylum approved these changes

2020-12-09 11:45 UTC, KrickRay requested changes

2020-12-09 11:45 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/shop-providers.component.ts
> +    terminalChanged() {
вроде методы не называем совершенным действием

2020-12-09 11:45 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/fetch-shop-providers/fetch-shop-providers.service.ts
> +    private getProviderInfos$ = new Subject<{ partyID: PartyID; shopID: ShopID }>();
info не имеет множественного числа

2020-12-09 11:45 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/fetch-shop-providers/fetch-shop-providers.service.ts
> +        this.providerInfos$.subscribe();
подписки лучше стараться перемещать в ngOnInit и наверное заюзать untilDestroy

2020-12-09 14:48 UTC, KrickRay approved these changes

2020-12-09 14:48 UTC, merged