Ft/party shops providers edit
rbkmoney/control-center pull request #223
Opened 2020-12-09 16:25 UTC by Roniakia

2020-12-16 10:57 UTC, KrickRay requested changes

2020-12-16 10:57 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/edit-terminal-decision/edit-terminal-decision.service.ts
> +    }) {
этот тип наверное нужно вынести

2020-12-16 10:57 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/remove-terminal-decision/remove-terminal-decision.service.ts
> +    }) {
и этот

2020-12-16 10:57 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/remove-terminal-decision/remove-terminal-decision.service.ts
> +    );
мне кажется на это явно нужно подписываться - сейчас удаление происходит неявно, за счет подписок на inProgress похоже

2020-12-16 10:57 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/remove-terminal-decision/remove-terminal-decision.service.ts
> +    );
и похоже нужно бы распилить

2020-12-16 10:57 UTC, KrickRay commented on src/app/thrift-services/damsel/services/edit-terminal-decision-property-for-shop.service.ts
> +    );
так же как и с removed

2020-12-16 10:57 UTC, KrickRay commented on src/app/thrift-services/damsel/services/edit-terminal-decision-property-for-shop.service.ts
> +                        return of('error');
чтобы не фильтровать моно вернуть `EMPTY`

2020-12-16 11:00 UTC, KrickRay commented on src/app/thrift-services/damsel/domain-typed-manager.ts
>              ),
может не в рамках этой задачи, но ожидалось, что DomainTypedManager будет распилен на отдельные сервисы, в данном случае этот метод должен был попасть в какой-то  ProviderService

2020-12-16 11:02 UTC, KrickRay commented on src/app/thrift-services/damsel/domain-typed-manager.ts
>              ),
там снизу тап tap(() => this.domainCacheService.forceReload()) не нужен, this.domainCacheService.commit уже содержит обновление после коммита

2020-12-16 11:06 UTC, KrickRay requested changes

2020-12-16 11:06 UTC, KrickRay commented on src/app/sections/shop-details/shop-providers/services/edit-terminal-decision/edit-terminal-decision.service.ts
> +    );
без подписки не будет работать, непонятно где она делается сейчас

2020-12-17 02:15 UTC, Roniakia commented on src/app/thrift-services/damsel/domain-typed-manager.ts
>              ),
DTM я просто удалю в след PR.

2020-12-18 08:36 UTC, KrickRay commented on src/app/thrift-services/damsel/domain-typed-manager.ts
> - */
why?

2020-12-18 08:37 UTC, KrickRay commented on src/app/thrift-services/damsel/domain-typed-manager.ts
> - */
все еще нужно разделить provider и terminal в разные сервисы

2020-12-18 08:39 UTC, KrickRay approved these changes
👍

2020-12-22 12:01 UTC, merged