FRONTEND-463. Deposit details
rbkmoney/control-center pull request #251
Opened 2021-03-17 11:14 UTC by DenisHedgehog

2021-03-17 15:07 UTC, KeinAsylum requested changes

2021-03-17 15:07 UTC, KeinAsylum commented on src/app/shared/components/destination-info/receive-wallet/receive-wallet.service.ts
> +        map(([id, wallets]) => wallets.result.filter((wallet) => wallet.id === id)[0]),
Получается что destinationID это walletID. Метод getWallets не умеет искать по walletID? Почему так сложно

2021-03-17 15:07 UTC, KeinAsylum commented on src/app/shared/components/destination-info/destination-info.component.ts
> +    selector: 'cc-destination-info',
Внутри идет получение кошелька по identityID и destinationID (который на самом деле walletID). Названно `destination-info`. А еще есть в протоколе отдельная сущность destination. И тут не про это совсем, а про кошелек. Какая-то путаница.

2021-03-17 17:13 UTC, DenisHedgehog commented on src/app/shared/components/destination-info/receive-wallet/receive-wallet.service.ts
> +        map(([id, wallets]) => wallets.result.filter((wallet) => wallet.id === id)[0]),
Не умеет, можно использовать не трифтовый метод getWalletByID, как в дашборде

2021-03-22 15:37 UTC, KeinAsylum requested changes
Открыл ПР по проблеме с конфликтом имен: https://github.com/rbkmoney/fistful-proto/pull/138

2021-03-22 15:37 UTC, KeinAsylum commented on src/app/shared/components/wallet-info/wallet-info.module.ts
> +export class WalletInfoModule {}
Внутри используется FistfulModule, странно не видеть зависимость от него тут

2021-03-26 08:20 UTC, KeinAsylum approved these changes

2021-03-26 08:21 UTC, merged