FRONTEND-465. Reverts list
rbkmoney/control-center pull request #253
Opened 2021-03-26 11:19 UTC by DenisHedgehog

2021-03-26 11:24 UTC, KeinAsylum commented
<img width="768" alt="Frame 1" src="https://user-images.githubusercontent.com/3588113/112624651-f6859c00-8e3e-11eb-9bb9-311b1635eb68.png">

2021-03-26 13:50 UTC, KrickRay requested changes

2021-03-26 13:50 UTC, KrickRay commented on src/app/thrift-services/fistful/fistful-stat.service.ts
> +    private readonly REVERTS_SEARCH_LIMIT = 5;
объявляем такие константы вне, а здесь в обычном кейсе используем

2021-03-26 13:50 UTC, KrickRay commented on src/app/thrift-services/fistful/fistful-stat.service.ts
> +    private readonly REVERTS_SEARCH_LIMIT = 5;
в идеале все таки ДиАй использовать

2021-03-26 13:50 UTC, KrickRay commented on src/app/sections/deposit-details/reverts/services/fetch-reverts/fetch-reverts.service.ts
> +    }
не понятно зачем такой метод выделять, еще и private static

2021-03-26 13:50 UTC, KrickRay commented on src/app/thrift-services/fistful/fistful-stat.service.ts
>              } as QueryDSL),
вижу что есть готовый метод createDSL(

2021-03-26 13:52 UTC, KrickRay commented on src/app/thrift-services/fistful/fistful-stat.service.ts
> +    ): Observable<FetchResult<RevertState>> {
весьма странно что трифтовый сервис возвращает FetchResult

2021-03-26 13:53 UTC, KrickRay commented on src/app/thrift-services/fistful/fistful-stat.service.ts
> +                        size: this.DEPOSITS_SEARCH_LIMIT.toString(),
это можно в аргументы перенести с дефолтным значением

2021-03-26 13:57 UTC, KrickRay commented
мы старались отходить от маппинга камелкейса в снейк а напрямую использовать трифтовые типы (в снэйккейсе)
здесь уже старый код наверное не стоит трогать но новый нужно с учетом этого писать

2021-03-26 13:59 UTC, KrickRay commented on src/app/thrift-services/fistful/fistful-stat.service.ts
> +                        size: this.REVERTS_SEARCH_LIMIT.toString(),
и это тоже можно в аргументах иметь

можно избавиться от констант в теле класса

2021-03-31 12:49 UTC, KeinAsylum approved these changes

2021-03-31 12:53 UTC, KrickRay approved these changes

2021-03-31 13:04 UTC, merged