FRONTEND-507: New thrift client integration
rbkmoney/control-center pull request #259
Opened 2021-04-07 17:31 UTC by KeinAsylum

2021-04-08 08:00 UTC, KeinAsylum commented
Зависит от https://github.com/rbkmoney/fistful-proto/pull/141

2021-04-08 15:42 UTC, DenisHedgehog commented on src/app/api/fistful/wallet/management.service.ts
> +    get(walletID: string, range = new EventRange()): Observable<WalletState> {
Метод так назван чтобы не было расхождений в названиях с протоколом?

2021-04-08 15:44 UTC, DenisHedgehog submitted a review, later dismissed

2021-04-09 08:05 UTC, KeinAsylum commented on src/app/api/fistful/wallet/management.service.ts
> +    get(walletID: string, range = new EventRange()): Observable<WalletState> {
Да, решил сделать близко к протоколу

2021-04-09 09:16 UTC, KrickRay requested changes

2021-04-09 09:16 UTC, KrickRay commented on src/app/api/fistful/wallet/management.service.ts
> +}
а в чем смысл такого кардинального изменения подхода? стало сложнее, а в том сервисе единственное что нужно было изменить - это хранить connection

2021-04-09 09:16 UTC, KrickRay commented on src/app/api/connection-utils/to-connect-options.ts
> +});
если это конфиг то по нашей логике это должно передаваться через токен

2021-04-09 15:23 UTC, KrickRay approved these changes

2021-04-09 15:29 UTC, merged