FR-641. Add country to international legal entity
rbkmoney/control-center pull request #271
Opened 2021-06-16 14:56 UTC by DenisHedgehog

2021-06-18 13:43 UTC, KrickRay requested changes

2021-06-18 13:43 UTC, KrickRay commented on src/app/shared/components/party-modification-forms/contract/legal-entity/international-legal-entity/international-legal-entity.component.ts
> +        // eslint-disable-next-line @typescript-eslint/unbound-method
убери эти игноры я поправлю правило - там нужно игнорировать сатаические методы

2021-06-18 13:43 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
вот такой игнор варнов вообще не решение, если уж ты не поправил то оставь варнинг

2021-06-18 13:43 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +};
вроде решение норм, но все это Object.assign, merge бесполезны, ссылки не поменяются

2021-06-18 13:43 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +};
либо копируй объект

2021-06-18 13:43 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +};
либо упрости до обычного присваивания свойства

2021-06-18 13:44 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +};
предыдущий либо применим и для склонированного объекта

2021-06-18 16:12 UTC, KrickRay commented
На редактирование и создание одна форма?

2021-06-21 08:03 UTC, DenisHedgehog commented
> На редактирование и создание одна форма?

Да

2021-06-21 09:52 UTC, KrickRay approved these changes
Все ок, единственное можно было бы добавь TODO над prepare функциями

2021-06-21 09:55 UTC, KrickRay requested changes

2021-06-21 09:55 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +        const country = new CountryRef({ id: CountryCode[countryCode] });
почему создание CountryRef здесь происходит?

2021-06-21 09:56 UTC, KrickRay commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +        const country = new CountryRef({ id: CountryCode[countryCode] });
есть же место где создается трифт объект, здесь должно быть только 
```suggestion
        const country = { id: CountryCode[countryCode] };
```

2021-06-21 10:17 UTC, DenisHedgehog commented on src/app/shared/components/party-modification-creator/create-modification-dialog/prepare-modifications-to-backend.ts
> +        const country = new CountryRef({ id: CountryCode[countryCode] });
А где ты предлагаешь его создавать?

2021-06-22 15:25 UTC, KeinAsylum approved these changes

2021-06-23 14:45 UTC, KrickRay approved these changes

2021-06-23 14:47 UTC, merged